# Generated by Django 4.2.13 on 2024-06-11 17:00

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_path_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='login',
            field=models.CharField(default='', error_messages={'Ваш логин не удовлетворяет требованиям:логин — только латинские буквы и цифры, первый символ — буква, длина от 4 до 20 символов'}, max_length=20, unique=True, validators=[django.core.validators.RegexValidator(code='no match', regex='^[a-zA-z]([a-zA-Z]|[0-9]){3,20}$')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='path',
            field=models.CharField(default='/<django.db.models.query_utils.DeferredAttribute object at 0x000001D30A9A31F0>', max_length=500),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
